config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#show"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :events
  resources :organizations, only: [:index, :show, :edit, :update, :destroy] do
    resources :contacts, only: [:new, :create, :edit, :update, :destroy]
  end
  get '/contacts' => 'contacts#index'

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :organization
  has_many :contacts, through: :organization

  accepts_nested_attributes_for :organization

  validates :name, presence: true

  def self.search_by_timeframe (current_user)
    Event.where(date: (Date.today - 30)..(Date.today), user_id: current_user)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.events.all.sort_by {|e| e.date}.reverse
    @events_by_timeframe = Event.search_by_timeframe(current_user.id)
  end

  def show
  end

  def new
    @event = Event.new
    @event.build_organization
    @event.organization.contacts.build
    @event.organization.contacts.build
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      @event.organization.contacts.build
      @event.organization.contacts.build
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
  def event_params
    event = params[:event]
    @event_date = Date.new event["date(1i)"].to_i, event["date(2i)"].to_i, event["date(3i)"].to_i
    if !event["follow_up_date(1i)"].empty?
      @follow_up_date = Date.new event["follow_up_date(1i)"].to_i, event["follow_up_date(2i)"].to_i, event["follow_up_date(3i)"].to_i
    end
    params.require(:event).permit(:name, :notes, :follow_up, :user_id, :organization_attributes => [:name, :location, :contacts_attributes => [:name, :phone, :email, :notes]]).merge(date: @event_date, follow_up_date: @follow_up_date)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def check_current_user
    @event = Event.find(params[:id])
    if current_user.id != @event.user_id
      redirect_to events_path
    end
  end

end

app/helpers/event_helper.rb
module EventHelper

  def past_due(event)
    if !event.follow_up_date.nil? && event.follow_up_date < Date.today
      link_to "PAST DUE", event_path(event)
    else
      link_to event.name, event_path(event)
    end
  end

  def li_id_past_due(event)
    if !event.follow_up_date.nil? && event.follow_up_date < Date.today
      "id=past-due"
    end
  end


  def display_follow_up_date(event)
    if !event.follow_up_date.nil?
      presentable_date(event.follow_up_date)
    else
      "N/A"
    end
  end

  def follow_up_display(event)
    if event.follow_up == true
      "Yes"
    else
      "No"
    end
  end
end

app/views/events/_formerrors.html.erb
<% if @event.errors.any? %>
  <div id= "error_explanation" >
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being saved: </h2>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render 'formerrors' %>
<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :date %>
  <%= f.date_select :date %>
  <br><br>
  <%= f.label :follow_up, "Follow Up Needed?" %>
  <%= f.check_box :follow_up %>
  <%= f.label :follow_up_date %>
  <%= f.date_select :follow_up_date, :include_blank => true %>
  <br><br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br><br>
  <hr>
  <%= hidden_field_tag "event[user_id]", current_user.id %>
  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
<h1>List of Events</h1>
<h4><%= link_to "New Event", new_event_path %></h4>
<hr>
<ul>
  <% @events.each do |event| %>
    <li <%= li_id_past_due(event) %> ><%= presentable_date(event.date) %> - <%= event.organization.name %> - <%= link_to event.name, event_path(event) %></li>
  <% end %>
</ul>

<% @events_by_timeframe.each do |event| %>
  <%= event.name %><br>
<% end %>

app/views/events/new.html.erb
<h1>Add an Event</h1>
<%= render 'formerrors' %>
<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :date %>
  <%= f.date_select :date %>
  <br><br>
  <%= f.label :follow_up, "Follow Up Needed?" %>
  <%= f.check_box :follow_up %>
  <%= f.label :follow_up_date %>
  <%= f.date_select :follow_up_date, :include_blank => true %>
  <br><br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br><br>
  <hr>

  <h4>Organization Information</h4>
  <%= f.fields_for :organization do |org_builder| %>
    <%= org_builder.label :name %>
    <%= org_builder.text_field :name %>
    <br><br>
    <%= org_builder.label :location, "City or Area" %>
    <%= org_builder.text_field :location %>
    <br><br>

    <h4>Contacts Information</h4>
    <div class="contacts">
      <%= org_builder.fields_for :contacts do |contact_builder| %>
        <div>
        <%= contact_builder.label :name %>
        <%= contact_builder.text_field :name %>
        <br><br>
        <%= contact_builder.label :phone %>
        <%= contact_builder.text_field :phone %>
        <br><br>
        <%= contact_builder.label :email %>
        <%= contact_builder.email_field :email %>
        <br><br>
        <%= contact_builder.label :notes%>
        <%= contact_builder.text_area :notes%>
        <br>
        </div>
      <% end %>
    </div>
  <% end %>
  <br><br>
  <hr>
  <br>
  <%= hidden_field_tag "event[user_id]", current_user.id %>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<hr>
<p>Event Date: <%= presentable_date(@event.date) %></p>
<p>Organization: <%= link_to @event.organization.name, organization_path(@event.organization) %></p>
<hr>
<p>Notes: <%= @event.notes %></p>
<p>Follow Up Needed? <strong><%= follow_up_display(@event) %></strong></p>
<p>Follow Up By: <%= display_follow_up_date(@event) %></p>
<hr>
<%= link_to "Edit Event", edit_event_path(@event) %><br>
<%= link_to "Delete Event", event_path(@event), :method => 'delete' %>