config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#show"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :events
  resources :organizations, only: [:index, :show, :edit, :update, :destroy] do
    resources :contacts, only: [:new, :create, :edit, :update, :destroy]
  end
  get '/contacts' => 'contacts#index'

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :events
  has_many :contacts
  has_many :user, through: :events
  accepts_nested_attributes_for :contacts, reject_if: proc { |attributes| attributes['name'].blank? }

  validates :name, uniqueness: true

  def contacts_attibutes=(contacts_attibutes)
    if !contacts_attributes.name.empty?
      contacts_attributes.values.each do |contact_attribute|
        contact = Contact.find_or_create_by(contact_attribute)
        self.contacts << contact
      end
    end
  end

  def self.search_by_location(query, current_user)
    self.select do |organization|
      (organization.user_ids[0] == current_user) && (organization.location.downcase.include? query)
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user, only: [:show, :edit, :update, :destroy]


  def index
    @organizations = current_user.organizations.all.sort_by {|i| i.name}
    if !@organizations.empty? && !params[:query].nil?
      @organizations = Organization.search_by_location(params[:query], current_user.id)
    else
      @organizations
    end
  end

  def show
  end

  def edit
  end

  def update
    if @organization.update(organization_params)
      redirect_to organization_path(@organization)
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path
  end

  private
  def organization_params
    params.require(:organization).permit(:name, :location)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def check_current_user
    @organization = Organization.find(params[:id])
    if current_user.id != @organization.user_ids[0]
      redirect_to organizations_path
    end
  end

end

app/views/organizations/_searchform.html.erb
<%= form_tag organizations_path, method: :get do %>
  <strong>Search by Location: </strong><br>
  <%= text_field_tag :query, params[:query], placeholder: "City or Area" %>
  <%= submit_tag "Search" %>
<% end %>

app/views/organizations/edit.html.erb
<h1>Edit Organization</h1>
<%= form_for @organization do |org_builder| %>
  <%= org_builder.label :name %>
  <%= org_builder.text_field :name %>
  <br><br>
  <%= org_builder.label :location %>
  <%= org_builder.text_field :location %>
  <br><br>
  <%= org_builder.submit %>
<% end %>

app/views/organizations/index.html.erb
<h1>List of Organizations</h1>
<%= render 'searchform' %>
<br>
<hr>
<table>
  <tr>
    <th>Organization</th>
    <th>Location</th>
  </tr>
  <% @organizations.each do |organization| %>
    <tr>
      <td><%= link_to organization.name, organization_path(organization) %></td>
      <td><%= organization.location %></td>
    </tr>
  <% end %>
</table>

app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>
<h4><%= @organization.location %></h4>
<%= link_to "Edit Organization", edit_organization_path(@organization) %>
<hr>
<h2>Contacts</h2>
<%= link_to "New Contact", new_organization_contact_path(@organization) %>
<hr>
<br>
<div class = "contacts">
  <% @organization.contacts.each do |contact| %>
    <div>
      <strong><%= contact.name %></strong>
      <p><%= contact.phone %></p>
      <p><%= contact.email %><p>
      <p>Notes: <%= contact.notes %><p>
      <%= link_to "Edit Contact", edit_organization_contact_path(@organization, contact) %><br>
      <%= link_to "Delete Contact", organization_contact_path(@organization, contact), :method => 'delete' %><br>
    </div>
  <% end %>
</div>