config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#show"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :events
  resources :organizations, only: [:index, :show, :edit, :update, :destroy] do
    resources :contacts, only: [:new, :create, :edit, :update, :destroy]
  end
  get '/contacts' => 'contacts#index'

end

app/views/layouts/_header.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Events", events_path %></li>
    <li><%= link_to "Organizations", organizations_path %></li>
    <li><%= link_to "Contacts", contacts_path %></li>
    <li><%= link_to "Account", edit_user_registration_path %></li>
    <li><%= link_to "Log Out", destroy_user_session_path, :method => 'delete' %></li>
    <p class="user">Currently logged in as: <%= current_user.name %></p>
  </ul>
</nav>

app/views/layouts/_welcome_header.html.erb
<h1 class='welcome'>Welcome to Networker</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Networker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <div class= "wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
  <footer>
    <strong>Networker, 2018</strong>
    <br>Created by Amanda Ackerman
  </footer>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Networker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>
<body>
  <div class= "wrapper">
    <%= welcome_header %>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

    <%= yield %>

    <%= link_to("Sign out", destroy_user_session_path, :method => 'delete') %>
  </div>
</body>
</html>